### PR TITLE
update test-sampleMetadata

### PR DESCRIPTION
**Pull request by sdgamboa**
**Why are you submitting this pull request**
This pull request addresses the creation of unit tests for study metadata/combined metadata methods.

**Is this pull request related to a bug report**
No.

**Is this pull request related to a feature request**
Yes. This pull request is related to issue #219.

**Additional context**
First draft unit tests checking that:
+ All studies from curatedMetagenomicData (in the [metadata.csv](https://github.com/waldronlab/curatedMetagenomicData/blob/master/inst/extdata/metadata.csv) file) are present in sampleMetadata.
+ All of the [required columns](https://github.com/waldronlab/curatedMetagenomicDataCuration/blob/master/inst/extdata/template.csv) are present in sampleMetadata.
+ sampleMetadata and combined_metadata are the same.

The combined_metadata file was updated by running the script [combined_metadata.R](https://github.com/waldronlab/curatedMetagenomicData/blob/master/data-raw/combined_metadata.R)

### CODE REVIEW

**Comment by sdgamboa** [comment]
@lwaldron  The test failed because it uses a file from the `curatedMetagenomicDataCuration` package. I tried adding it to the suggests list in DESCRIPTION, but that didn't work (I guess because the package is not released?). I'm not sure if this test is required, though (below).

I'll delete that test and the suggestion of curatedMetagenomicDataCuration in DESCRIPTION.

I think there are some other [runs](https://github.com/waldronlab/curatedMetagenomicData/runs/2527807298?check_suite_focus=true#logs) that fail, related to the data-raw/sysdata.R script, probably dara-raw/sampleMetadata.R script as well.


```r
test_that("all required columns are present in sampleMetadata", {

    requiredColumns <- system.file("extdata/template.csv", package = "curatedMetagenomicDataCuration") %>%
        read.csv() %>%
        subset(requiredness == "required") %>%
        .[["col.name"]]

    expect_true(all(requiredColumns %in% colnames(sampleMetadata)))

})
```

**Comment by lwaldron** [comment]
You can't include a non CRAN/Bioconductor package in the DESCRIPTION, but for the test you can use the raw URL (https://raw.githubusercontent.com/waldronlab/curatedMetagenomicDataCuration/master/inst/extdata/template.csv) directly in `download.file` or `read.csv`.

**Comment by sdgamboa** [comment]
@lwaldron Thanks! I'll use the direct file instead.

**Comment by schifferl** [comment]
I added this unit test in 7a2a2c3, will close for now and we can discuss at the meeting tomorrow.

**Pull request closed without merging**
