### PR TITLE
Combine update combined_metadata and data-raw actions

### LINKED ISSUE #200: restore automated PR GitHub Action
New workflow from @schifferl for `curated_metadata` ensures only keeping metadata with data in ExperimentHub, but is lacking CRON, automated PR, badge. Desired functionality is now split across two workflows that need to be merged:
1. https://github.com/waldronlab/curatedMetagenomicData/blob/master/.github/workflows/update_combined_metadata.yaml (@jwokaty)
2. https://github.com/waldronlab/curatedMetagenomicData/blob/master/.github/workflows/data-raw.yaml (@schifferl)

### PR DESCRIPTION
**Pull request by jwokaty**
This PR combines the actions to update combined_metadata and data-raw to make update-curation.yml. Note that .github/workflows/data-raw.yml is removed and that the curation file is still called sampleMetadata.rda, although it may be changed back to combined_metadata.rda via #196. The action uses cMDC's checkCuration, which is currently failing because it expects column "dataset_name" but has "studyName".

Closes #200.

### CODE REVIEW

**Review by schifferl — COMMENTED** [review]
Why are we doing the Test curation step? Doesn't this happen in the curation repo? I think we need to remove the step and depend on the metadata being correct from `inst/curated` in the curation repo.

**Comment by lwaldron** [comment]
curatedMetagenomicDataCuration provides a vignette and badge to help curators fix errors, but it provides no guarantees of validity of metadata - curators can and do commit preliminary work then fix it sometime later. There is the additional issue that by the time the PR is reviewed here, the curation repo may have been changed further, but still manual review of the PR is desirable because there are limitations of the automatic checks that we sometimes over-ride by either accepting language that fails, or rejecting language that passes (for example see https://github.com/waldronlab/curatedMetagenomicDataCuration/issues/2).  To have an assurance of valid metadata in curatedMetagenomicData, tests have to be done in its own workflow.

**Comment by jwokaty** [comment]
If and after this is approved, I'd also like to merge this myself so I can rebase it on master when it has the changes for #212 and #211 so I can handle the merge conflicts. This will make for a cleaner history.

**Review by schifferl — APPROVED** [review]
Approved, but we should probably encapsulate the checking logic in a script rather than the action itself in the future.

**Comment by lwaldron** [comment]
> we should probably encapsulate the checking logic in a script rather than the action itself in the future.

Which part of the logic? The check itself already relies on the function `curatedMetagenomicDataCuration::checkCuration()`, this action is about running the check weekly and creating a badge and automatic pull request.

**Pull request merged**
