### PR TITLE
Renamed sampleMetadata back to combined_metadata

### PR DESCRIPTION
**Pull request by jwokaty**
Rename sampleMetadata back to combined_metadata. I left some remnants of sampleMeta, such as data-raw/sampleMetadata.R, but tried to change instances where we refer to the data frame.

### CODE REVIEW

**Review by lwaldron — APPROVED** [review]
Thanks @jwokaty! I'll request review and leave it to @schifferl to merge. Just to re-iterate my (strong) desire to make this change - I think by keeping this as an upgrade of curatedMetagenomicData instead of a new package ie curatedMetagenomicData3, we've committed to maintaining as much backward compatibility as possible and practical, and to going through the deprecation process for anything else. This package has quite a few users and we need to minimize their pain.

**Comment by jwokaty** [comment]
After/if this is approved, I would like to merge it myself because I want to rebase it on master after fetching the result of merging #212 to avoid merge conflicts.

**Review by schifferl — APPROVED** [review]
Looks like you found them all!

**Comment by schifferl** [comment]
This pull request can't be automatically merged because it has conflicts with the `master` branch, can you resolve them @jwokaty?

**Comment by jwokaty** [comment]
I noticed that even after removing most references to sampleMetadata and regenerating combined_metadata that when I installed and loaded the package with devtools that I still saw sampleMetadata was exported. Where could this sampleMetadata come from?

```{r}
devtools::install()
devtools::load_all()
curatedMetagenomicData::sampleMetadata # this is still valid
```

**Pull request merged**
