### PR TITLE
issue 195 - update mergeData function

### PR DESCRIPTION
**Pull request by sdgamboa**
+ Updated mergeData function and documentation.
+ NAMESPACE and DESCRIPTION files were updated as well.
+ This function was used to upload files of issue [121](https://github.com/waldronlab/curatedMetagenomicData/issues/121).

### CODE REVIEW

**Review by schifferl — CHANGES_REQUESTED** [review]
This pull request adds dependencies and is not how I've approached the merging in other areas of the pipeline (see https://github.com/waldronlab/curatedMetagenomicDataPipeline/blob/master/R/read_dir.R). I would want this method to pull out the colData and assay slots and then merge them with a `dplyr::full_join` (far faster than the method suggested here in my benchmarking).

I also wonder if we should be guiding users towards using a MultiAssayExperiment instead, I don't know that making an extra large SummarizedExperiment is the right approach.

**Comment by lwaldron** [comment]
(Tree)SummarizedExperiment and not MultiAssayExperiment is appropriate because it's all one data type and just a merge of a number of smaller (Tree)SummarizedExperiment objects - not intended for integrating different data types. This PR doesn't introduce any actual dependencies since `methods` and `Biobase` are already installed for any Bioconductor user and this is just making their imports explicit (and `tidyselect` was already an import, this just adds a comma to that line). I doubt that the benchmarking is as much of an issue here since the profiles are already merged by dataset so far fewer merges are being done than during dataset-building. Those methods can be substituted for performance enhancement, but it's not critical for releasing cMD 3.0. I certainly don't mind changing algorithms, but think we should merge the PR because it accomplishes the maintenance of functionality, and changing algorithms can be a follow-up performance enhancement that isn't critical for release.

**Review by lwaldron — APPROVED** [review]

**Comment by schifferl** [comment]
Hello @sdgamboa, @lwaldron, let me first start with an apology. I am so sorry to not merge your pull request @sdgamboa – I know it must have taken some work to straighten out that code and I don't mean to diminish your contribution in any way. There was some hard work there and it is certainly acknowledged.

I implemented this in 09b1b89 in a way that will be maintainable into the future and where we rely on a more tidyverse paradigm. The approach has few lines, runs faster, and does iteration with purrr instead of for loops. Again, I am sorry to supersede the work that was done, but want to prevent a few headaches in the future.

**Comment by sdgamboa** [comment]
Thanks, @schifferl! No need to apologize. I'm glad the updates have been made.

**Pull request closed without merging**
