### PR TITLE
Add filterByDataType

### LINKED ISSUE #216: add method for sample-level returns
**Is your feature request related to a problem? Please describe.**
Often in is desirable to return multiple studies merged together and filtered by some sample metadata criteria (e.g. `age >= 65`). A method to do this with a single method call currently does not exist in curatedMetagenomicData, but is likely (in my humble opinion) the feature most frequently implemented by users. It would allow for the comparison of samples in mega and meta analyses.

**Describe the solution you'd like**
If implemented this method would provide an interface similar to the `curatedMetagenomicData` method and allow for specification of data type (e.g. `gene_families`) and sample metadata conditions, as aforementioned. It might take unlimited conditions by the `...` argument and check them (logical `&` for multiple) before proceeding to downloading. To my mind the method would be named `selectWhere` in the spirit of SQL `SELECT * FROM table WHERE condition` syntax.

**Describe alternatives you've considered**
With the current API changes this is not so difficult to implement as a user, the process would be approximately as follows.

- Filter the `sampleMetadata` table based on specified conditions
- Pull the unique `dataset_names` from the table and paste `.gene_families` (or another data type) onto them
- Download the studies using the `curatedMetagenomicData` method
- Merge the studies using the `mergeData` method
- Filter the rows of the `TreeSummarizedExperiment` or `SummarizedExperiment` to equal the `sampleID` column of the `sampleMetadata` subset in the first step

**Additional context**
Having written the steps, it seems that they probably should be implemented (because they are common) and those are approximately the instructions. This issue replaces #130 which will be closed now.

### PR DESCRIPTION
**Pull request by jwokaty**
This is my initial pass. I would appreciate feedback to improve as I'm still learning R, Bioconductor, etc., and may not be familiar with conventions or the best way to do things.

I selected the second suggested function style--was the first way the more "R way" to approach the problem?. I wrote some documentation but I wanted to ask what would be better examples and test cases? I haven't tested a large dataset as the function sometimes kills my R session and I'm not sure yet if this is my bad programming or not enough memory.

One thing I noticed is that when I did the `selectWhere("relative_abundance", age >= 30, age <= 40, smoker == "yes")`, I noticed that I got NAs  for age in the result despite specifying that age should be >=30 and <= 40. Is this behavior expected?

Thanks for your feedback.

Closes #216.

### CODE REVIEW

**Comment by cmirzayi** [comment]
Yes this is expected base R behavior and I've always found it unintuitive. `dplyr::filter()` (https://dplyr.tidyverse.org/reference/filter.html) is an alternative that does not return NAs.

**Comment by lwaldron** [comment]
Nice, @jwokaty! I feel like many such questions about the filtering might come up. The filtering process might be more interactive and less likely to raise blame on your function for unexpected behavior if you ask the user to perform the filtering themselves on `combined_metadata`, and to provide the resulting data.frame (or tibble, or DataFrame, I forget :) ) as input to this function. As long as that data.frame contains columns dataset_name and sampleID (sample_id?) that are subsets of the original `combined_metadata`, we promise to return a (Tree)SummarizedExperiment with these same rows in its colData, in the same order.

**Comment by jwokaty** [comment]
@cmirzayi and @lwaldron Thanks for your feedback. I'm convinced now that I should rewrite so that the user filters to avoid confusion.

**Comment by jwokaty** [comment]
I've refactored to allow the user to filter first. The new function is called `filterByDataType`. I've also added a test, which is failing because I think there's an issue with `mergedData` that I've documented in #227.

**Comment by lwaldron** [comment]
This looks great, @jwokaty ! The only suggestions I would make, just out of paranoia, would be a couple additions to the test: 
1. `expect_true(is(result, "SummarizedExperiment"))` (this should pass whether the result is a SummarizedExperiment or TreeSummarizedExperiment)
2. do the same colData check that you did on age, also on dataset_name and sampleID (if I'm remembering correctly what those are called now)

**Review by schifferl — APPROVED** [review]

**Comment by schifferl** [comment]
Thank you @jwokaty, I am merging this now.

**Pull request merged**
